### PR TITLE
Length

### PR DESCRIPTION
**Pull request by brettz9**
Although my Windows machine doesn't let me complete the testing (the `cat` call in `package.json`), it seems the `maxLength`/`minLength` tests are now working.

I jumped through a few hoops to get GraphemeBreaker browserified and embedded properly.

### CODE REVIEW

**Comment by brettz9** [comment]
Meant to fix #5

**Comment by AlexeyGrishin** [comment]
Hi,

Thanks again for your help. I think using of that GraphebeBreaker is a good idea to process unicode strings. However inclusion of this library increases browser version 3 times. As far as not everyone needs support of minLength/maxLength for unicode I would think about naving this dependency optional - introduce something like plugin or just two compiled libs, one without unicode and one with unicode.

Let me think about it

**Comment by AlexeyGrishin** [comment]
What do you think if I will not include GrapheneBreaker into schemasaurus but instead will provide api to use it? I've prepared a branch to illustrate that: https://github.com/AlexeyGrishin/schemasaurus/tree/unicode_length#unicode-support

```
var s = require('schemasaurus');
var GraphemeBreaker = require('grapheme-breaker');

var strOfLength3 = "12a\u0301\u0302";
var schemaForLength3 = {maxLength: 3};
var unicodeValidator = s.newValidator(schemaForLength3, {
    strLength: function (str) {
        return GraphemeBreaker.countBreaks(str);
    }
});

console.log(unicodeValidator(strOfLength3));
```

**Comment by brettz9** [comment]
That could work--or might it be possible to supply flags to the build process which could conditionally install grapheme-breaker?

**Comment by brettz9** [comment]
I guess this can be closed now as per 1871ed126c225642a61278187ed8068bc88995b3 ?

**Comment by brettz9** [comment]
Your conditional support is fine by me. Will close.

**Pull request closed without merging**
